# Generated by Django 5.2.10 on 2026-01-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
