# Generated by Django 5.2.10 on 2026-01-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_in_stock_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('one_time_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('monthly_plan_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_100g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Price (100g)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_50g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Price (50g)'),
        ),
    ]
