import os
import django
from django.core.files.base import ContentFile
from dotenv import load_dotenv

# Load env vars
load_dotenv()

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'leafypop_project.settings')
django.setup()

from store.models import Product
from django.conf import settings

# Base Path for Static Images
STATIC_IMAGES_DIR = os.path.join('store', 'static', 'store', 'images')

# Mapping of product names to local filenames and their locations
image_mapping = {
    'Broccoli Microgreens': os.path.join(STATIC_IMAGES_DIR, 'brocallymicrogreen.png'),
    'Beetroot Microgreens': os.path.join(STATIC_IMAGES_DIR, 'beetrootmicrogreen.png'),
    'Sunflower Microgreens': os.path.join(STATIC_IMAGES_DIR, 'sunflowermicrogreen.png'),
    'Pea Shoot Microgreens': os.path.join(STATIC_IMAGES_DIR, 'peasoot microgreen.png'),
    'Radish Microgreens': os.path.join(STATIC_IMAGES_DIR, 'radish microgreen.png'),
    'Leafypop Mix Microgreens': os.path.join('media', 'products', 'mix_microgreen.jpeg'),
}

def restore_images():
    print("Starting Product Image Restoration to Cloudinary...")
    
    products = Product.objects.all()
    
    for product in products:
        if product.name in image_mapping:
            filepath = image_mapping[product.name]
            
            if os.path.exists(filepath):
                print(f"Uploading {filepath} for {product.name}...")
                try:
                    with open(filepath, 'rb') as f:
                        filename = os.path.basename(filepath)
                        product.image.save(filename, ContentFile(f.read()), save=True)
                    
                    # Force refresh from DB to see the URL generated by Cloudinary
                    product.refresh_from_db()
                    print(f"Success! {product.name} updated. URL: {product.image.url}")
                except Exception as e:
                    print(f"Error uploading {product.name}: {str(e)}")
            else:
                print(f"Warning: Local file not found at {filepath}")
        else:
            print(f"Skipping {product.name} (not in mapping)")

    print("\nRestoration complete!")

if __name__ == "__main__":
    restore_images()
